services:
 rustp:
  image: rust-test
  restart: always
  ports:
   - "8080:8080"
  depends_on:
   - redis
   - mysql

 redis:
  build:
   context: .
   dockerfile: Dockerfile.redis
# image: redis
  restart: always
  ports:
   - "6379:6379"

 mysql:
  image: mysql
  restart: always
  ports:
   - "3000:3306"
  volumes:
   - mysql_data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=121234
   - flux="mysql://root:121234@mysql/flux?ssl-mode=DISABLED"
   - plc="mysql://root:121234@mysql/plc?ssl-mode=DISABLED"
   - fluxVice="mysql://root:121234@mysql/fluxVice?ssl-mode=DISABLED"
   - REDIS_PASSWD="Iloveyouxuwu121234"
   - REDIS_URL="redis://:Iloveyouxuwu121234@redis"

volumes:
 mysql_data:
  external: true
