use std::collections::HashMap;
use actix_web::{post,get, web, Responder, HttpResponse,HttpRequest};
use redis::RedisResult;
use std::io::Write;
use chrono::{prelude::*, Duration};
use sqlx::{pool, MySql, MySqlPool};
use crate::models::{TempRecord::TempRecord,TurbineState::TurbineState,TempRecord::{DateTimeRange,DateTimeRng,HistoryData}};
use crate::models::redis_data::RedisState;
use crate::handlers::Verify::{verify,get_connection};
use crate::mapper::sql::get_data_in_range;
