produce:
  - tag: "flux"
    node: "ns=2;s=模拟器示例.函数.Ramp1"
  - tag: "fluxVice"
    node: "ns=2;s=模拟器示例.函数.Random2"
    # node: "ns=2;s=ForOPCUA.PLC.temperature"
  - tag: "switch"
    node: "ns=2;s=模拟器示例.函数.switch"
  - tag: "switchVice"
    node: "ns=2;s=模拟器示例.函数.switchVice"
    # node: "ns=2;s=ForOPCUA.PLC.switch"
  - tag: "setpoint"
    node: "ns=2;s=模拟器示例.函数.setpoint"
  - tag: "setpointVice"
    node: "ns=2;s=模拟器示例.函数.setpointVice"
    # node: "ns=2;s=ForOPCUA.PLC.setpoint"
test:
  - tag: "testBool"
    node: "ns=2;s=模拟器示例.函数.bool"
  - tag: "testDouble"
    node: "ns=2;s=模拟器示例.函数.test"
  - tag: "ramp1"
    node: "ns=2;s=模拟器示例.函数.Ramp1"

